name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: write # Needed to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred version

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate Documentation
        run: python scripts/generate_docs.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          # Optional: Keep history if you want to see previous deployments
          # keep_files: true
          # Optional: Custom CNAME if you have one
          # cname: your.custom.domain.com
